<a href="https://colab.research.google.com/github/ahsenozturk1/hi-work---odev/blob/main/Numpy_odev_ipynb_adl%C4%B1_not_defterinin_kopyas%C4%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##### 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5], dtype=int)
arr

array([1, 2, 3, 4, 5])

In [ ]:
print("Array boyutu (ndim):", arr.ndim)

print("Array eleman sayısı (size):", arr.size)

print("Array şekli (shape):", arr.shape)

Array boyutu (ndim): 1
Array eleman sayısı (size): 5
Array şekli (shape): (5,)


##### 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım.

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]



In [ ]:
import numpy as np

arr2d = np.array([[1, 2, 6, 7],
                  [4, 3, 9, 5]])

print("2D Array:")
print(arr2d)
print("Boyut sayısı (ndim):", arr2d.ndim)
print("Toplam eleman sayısı (size):", arr2d.size)
print("Shape (satır, sütun):", arr2d.shape)

2D Array:
[[1 2 6 7]
 [4 3 9 5]]
Boyut sayısı (ndim): 2
Toplam eleman sayısı (size): 8
Shape (satır, sütun): (2, 4)


In [ ]:
arr3d = np.array([[[7, 5, 14], [21, 8, 11]],
                  [[8, 6, 20], [14, 3, 9]]])

print("\n3D Array:")
print(arr3d)
print("Boyut sayısı (ndim):", arr3d.ndim)
print("Toplam eleman sayısı (size):", arr3d.size)
print("Shape (katman, satır, sütun):", arr3d.shape)


3D Array:
[[[ 7  5 14]
  [21  8 11]]

 [[ 8  6 20]
  [14  3  9]]]
Boyut sayısı (ndim): 3
Toplam eleman sayısı (size): 12
Shape (katman, satır, sütun): (2, 2, 3)


##### 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [ ]:
#İki boyutlu arraydaki 2 elemanına ulaşalım
print(arr2d[0, 1])

2


In [ ]:
#İki boyutlu arraydaki 7 elemanına ulaşalım
print(arr2d[0, 3])

7


In [ ]:
#Üç boyutlu arraydaki 9 elemanına ulaşalım
print(arr3d[1, 1, 2])

9


In [ ]:
#Üç boyutlu arraydaki 5 elemanına ulaşalım
print(arr3d[0, 0, 1])

5


##### 4. Arrayler üzerinde slicing işlemi uygulayalım.

In [ ]:
#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım
print(arr2d[0, 1:3])

[2 6]


In [ ]:
#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım
print(arr2d[1, 1:4])

[3 9 5]


In [ ]:
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım
print(arr3d[0, 1, :])

[21  8 11]


In [ ]:
#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım
print(arr2d[1, 1:4])

[3 9 5]


##### 5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [ ]:
arr1 = np.zeros((5, 3), dtype=int)  # sıfırlardan oluşan
arr2 = np.ones((5, 3), dtype=int)   # birlerden oluşan

print("Array 1:\n", arr1)
print("\nArray 2:\n", arr2)

Array 1:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

Array 2:
 [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
arr_row_concat = np.concatenate((arr1, arr2), axis=0)

print("\nSatır bazında birleştirilmiş array:\n", arr_row_concat)


Satır bazında birleştirilmiş array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
arr_col_concat = np.concatenate((arr1, arr2), axis=1)

print("\nSütun bazında birleştirilmiş array:\n", arr_col_concat)


Sütun bazında birleştirilmiş array:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
